/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hlserver_constants.h"

namespace hlserver {

const hlserverConstants g_hlserver_constants;

hlserverConstants::hlserverConstants() {
  SERVER_PORT = 9822;

  BASE_PATH = "/srv/hlstreamer";

}

} // namespace

