/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hlserver_TYPES_H
#define hlserver_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace hlserver {

struct JobType {
  enum type {
    ON_DEMAND = 1,
    LIVE_STREAM = 2,
    SCHEDULING = 3
  };
};

extern const std::map<int, const char*> _JobType_VALUES_TO_NAMES;

struct JobStatusType {
  enum type {
    INVALID = 1,
    ACCEPTED = 2,
    IN_PROGRESS = 3,
    FINISHED = 4,
    ERROR = 6
  };
};

extern const std::map<int, const char*> _JobStatusType_VALUES_TO_NAMES;

typedef int8_t i8;

class VideoProperties;

class AudioProperties;

class Properties;

class Job;

class JobStatus;

class TranscodingError;

class JobError;

typedef struct _VideoProperties__isset {
  _VideoProperties__isset() : width(false), height(false), keyInterval(false), bitrate(false), framerate(false), noiseReduction(false) {}
  bool width;
  bool height;
  bool keyInterval;
  bool bitrate;
  bool framerate;
  bool noiseReduction;
} _VideoProperties__isset;

class VideoProperties {
 public:

  static const char* ascii_fingerprint; // = "702A300A7FCCFAD34992E0E52FD1FA78";
  static const uint8_t binary_fingerprint[16]; // = {0x70,0x2A,0x30,0x0A,0x7F,0xCC,0xFA,0xD3,0x49,0x92,0xE0,0xE5,0x2F,0xD1,0xFA,0x78};

  VideoProperties(const VideoProperties&);
  VideoProperties& operator=(const VideoProperties&);
  VideoProperties() : width(0), height(0), keyInterval(0), bitrate(0), framerate(0), noiseReduction(0) {
  }

  virtual ~VideoProperties() throw();
  int16_t width;
  int16_t height;
  i8 keyInterval;
  int16_t bitrate;
  int16_t framerate;
  i8 noiseReduction;

  _VideoProperties__isset __isset;

  void __set_width(const int16_t val);

  void __set_height(const int16_t val);

  void __set_keyInterval(const i8 val);

  void __set_bitrate(const int16_t val);

  void __set_framerate(const int16_t val);

  void __set_noiseReduction(const i8 val);

  bool operator == (const VideoProperties & rhs) const
  {
    if (!(width == rhs.width))
      return false;
    if (!(height == rhs.height))
      return false;
    if (!(keyInterval == rhs.keyInterval))
      return false;
    if (!(bitrate == rhs.bitrate))
      return false;
    if (!(framerate == rhs.framerate))
      return false;
    if (!(noiseReduction == rhs.noiseReduction))
      return false;
    return true;
  }
  bool operator != (const VideoProperties &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VideoProperties & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(VideoProperties &a, VideoProperties &b);

typedef struct _AudioProperties__isset {
  _AudioProperties__isset() : bitrate(false), channels(false) {}
  bool bitrate;
  bool channels;
} _AudioProperties__isset;

class AudioProperties {
 public:

  static const char* ascii_fingerprint; // = "2F32B8B152B4427223DB9D670291659B";
  static const uint8_t binary_fingerprint[16]; // = {0x2F,0x32,0xB8,0xB1,0x52,0xB4,0x42,0x72,0x23,0xDB,0x9D,0x67,0x02,0x91,0x65,0x9B};

  AudioProperties(const AudioProperties&);
  AudioProperties& operator=(const AudioProperties&);
  AudioProperties() : bitrate(0), channels(0) {
  }

  virtual ~AudioProperties() throw();
  int16_t bitrate;
  i8 channels;

  _AudioProperties__isset __isset;

  void __set_bitrate(const int16_t val);

  void __set_channels(const i8 val);

  bool operator == (const AudioProperties & rhs) const
  {
    if (!(bitrate == rhs.bitrate))
      return false;
    if (!(channels == rhs.channels))
      return false;
    return true;
  }
  bool operator != (const AudioProperties &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AudioProperties & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(AudioProperties &a, AudioProperties &b);

typedef struct _Properties__isset {
  _Properties__isset() : inFile(false), baseUri(false), video(false), audio(false) {}
  bool inFile;
  bool baseUri;
  bool video;
  bool audio;
} _Properties__isset;

class Properties {
 public:

  static const char* ascii_fingerprint; // = "81AB8A960ED2C0E3679A7B9DA5240FB3";
  static const uint8_t binary_fingerprint[16]; // = {0x81,0xAB,0x8A,0x96,0x0E,0xD2,0xC0,0xE3,0x67,0x9A,0x7B,0x9D,0xA5,0x24,0x0F,0xB3};

  Properties(const Properties&);
  Properties& operator=(const Properties&);
  Properties() : inFile(), baseUri() {
  }

  virtual ~Properties() throw();
  std::string inFile;
  std::string baseUri;
  VideoProperties video;
  AudioProperties audio;

  _Properties__isset __isset;

  void __set_inFile(const std::string& val);

  void __set_baseUri(const std::string& val);

  void __set_video(const VideoProperties& val);

  void __set_audio(const AudioProperties& val);

  bool operator == (const Properties & rhs) const
  {
    if (!(inFile == rhs.inFile))
      return false;
    if (!(baseUri == rhs.baseUri))
      return false;
    if (!(video == rhs.video))
      return false;
    if (!(audio == rhs.audio))
      return false;
    return true;
  }
  bool operator != (const Properties &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Properties & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Properties &a, Properties &b);

typedef struct _Job__isset {
  _Job__isset() : id(false), type(false) {}
  bool id;
  bool type;
} _Job__isset;

class Job {
 public:

  static const char* ascii_fingerprint; // = "DFA40D9D2884599F3D1E7A57578F1384";
  static const uint8_t binary_fingerprint[16]; // = {0xDF,0xA4,0x0D,0x9D,0x28,0x84,0x59,0x9F,0x3D,0x1E,0x7A,0x57,0x57,0x8F,0x13,0x84};

  Job(const Job&);
  Job& operator=(const Job&);
  Job() : id(0), type((JobType::type)0) {
  }

  virtual ~Job() throw();
  int64_t id;
  JobType::type type;

  _Job__isset __isset;

  void __set_id(const int64_t val);

  void __set_type(const JobType::type val);

  bool operator == (const Job & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(type == rhs.type))
      return false;
    return true;
  }
  bool operator != (const Job &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Job & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Job &a, Job &b);

typedef struct _JobStatus__isset {
  _JobStatus__isset() : type(false), jobId(false), message(false) {}
  bool type;
  bool jobId;
  bool message;
} _JobStatus__isset;

class JobStatus {
 public:

  static const char* ascii_fingerprint; // = "5903DB663ABC109180254BE53D624B46";
  static const uint8_t binary_fingerprint[16]; // = {0x59,0x03,0xDB,0x66,0x3A,0xBC,0x10,0x91,0x80,0x25,0x4B,0xE5,0x3D,0x62,0x4B,0x46};

  JobStatus(const JobStatus&);
  JobStatus& operator=(const JobStatus&);
  JobStatus() : type((JobStatusType::type)0), jobId(0), message() {
  }

  virtual ~JobStatus() throw();
  JobStatusType::type type;
  int64_t jobId;
  std::string message;

  _JobStatus__isset __isset;

  void __set_type(const JobStatusType::type val);

  void __set_jobId(const int64_t val);

  void __set_message(const std::string& val);

  bool operator == (const JobStatus & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (!(jobId == rhs.jobId))
      return false;
    if (__isset.message != rhs.__isset.message)
      return false;
    else if (__isset.message && !(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const JobStatus &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const JobStatus & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(JobStatus &a, JobStatus &b);

typedef struct _TranscodingError__isset {
  _TranscodingError__isset() : code(false), what(false) {}
  bool code;
  bool what;
} _TranscodingError__isset;

class TranscodingError : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  TranscodingError(const TranscodingError&);
  TranscodingError& operator=(const TranscodingError&);
  TranscodingError() : code(0), what() {
  }

  virtual ~TranscodingError() throw();
  int32_t code;
  std::string what;

  _TranscodingError__isset __isset;

  void __set_code(const int32_t val);

  void __set_what(const std::string& val);

  bool operator == (const TranscodingError & rhs) const
  {
    if (!(code == rhs.code))
      return false;
    if (!(what == rhs.what))
      return false;
    return true;
  }
  bool operator != (const TranscodingError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TranscodingError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TranscodingError &a, TranscodingError &b);

typedef struct _JobError__isset {
  _JobError__isset() : jobId(false), what(false) {}
  bool jobId;
  bool what;
} _JobError__isset;

class JobError : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "727CAEA8265A5DE67DBC931F55CD8753";
  static const uint8_t binary_fingerprint[16]; // = {0x72,0x7C,0xAE,0xA8,0x26,0x5A,0x5D,0xE6,0x7D,0xBC,0x93,0x1F,0x55,0xCD,0x87,0x53};

  JobError(const JobError&);
  JobError& operator=(const JobError&);
  JobError() : jobId(0), what() {
  }

  virtual ~JobError() throw();
  int64_t jobId;
  std::string what;

  _JobError__isset __isset;

  void __set_jobId(const int64_t val);

  void __set_what(const std::string& val);

  bool operator == (const JobError & rhs) const
  {
    if (!(jobId == rhs.jobId))
      return false;
    if (!(what == rhs.what))
      return false;
    return true;
  }
  bool operator != (const JobError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const JobError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(JobError &a, JobError &b);

} // namespace

#endif
