/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hlserver_CONSTANTS_H
#define hlserver_CONSTANTS_H

#include "hlserver_types.h"

namespace hlserver {

class hlserverConstants {
 public:
  hlserverConstants();

  int16_t SERVER_PORT;
  std::string BASE_PATH;
};

extern const hlserverConstants g_hlserver_constants;

} // namespace

#endif
