libm3u8: m3u8.h File Reference
m3u8.h File Reference
#include <stdio.h>
#include <stdint.h>
Data Structures
struct InfRecord
struct PlaylistRecords
struct Playlist
struct IndexStreamRecord
struct IndexStreamList
Enumerations
enum XPlaylistType {
DEFAULT = 0x00, VOD, EVENT, LIVE,
VARIANT
}
Functions
int8_t inf_init (InfRecord **record)
int8_t inf_set_length (InfRecord **record, const float length)
int8_t inf_set_name (InfRecord **record, const char *name)
int8_t inf_set_path (InfRecord **record, const char *path)
int8_t inf_destroy (InfRecord **record)
int8_t record_list_init (PlaylistRecords **head)
int8_t record_list_add (PlaylistRecords **cur, InfRecord *data)
int8_t record_list_add_more (PlaylistRecords **cur, const float length, const char *name, const char *path)
int8_t record_list_remove_at (PlaylistRecords **head, uint16_t index)
int8_t record_list_remove_first_n (PlaylistRecords **head, uint16_t n)
int8_t record_list_destroy (PlaylistRecords **head)
XPlaylistType playlist_type_from (const char *str)
const char * playlist_type_str (const XPlaylistType type)
int8_t playlist_records_init (Playlist *playlist)
int8_t playlist_records_add (Playlist *playlist, const float length, const char *name, const char *path)
int8_t playlist_records_destroy (Playlist *playlist)
int8_t playlist_write (Playlist *playlist, const char *filename)
int8_t playlist_write_to (Playlist *playlist, FILE *out)
int8_t playlist_load (Playlist *playlist, const char *filename)
int8_t playlist_load_from (Playlist *playlist, FILE *in)
int8_t index_stream_record_set_program_id (IndexStreamRecord **cur, int8_t program_id)
int8_t index_stream_record_set_bandwidth (IndexStreamRecord **cur, uint64_t bandwidth)
int8_t index_stream_record_set_codecs (IndexStreamRecord **cur, const char *codecs)
int8_t index_stream_record_set_path (IndexStreamRecord **cur, const char *path)
int8_t index_stream_list_init (IndexStreamList *list)
int8_t index_stream_list_add (IndexStreamList *list, int8_t program_id, uint64_t bandwidth, const char *codecs, const char *path)
int8_t index_stream_list_destroy (IndexStreamList *list)
int8_t index_stream_list_write (IndexStreamList *list, const char *filename)
int8_t index_stream_list_write_to (IndexStreamList *list, FILE *out)
int8_t index_stream_list_load (IndexStreamList *list, const char *filename)
int8_t index_stream_list_load_from (IndexStreamList *list, FILE *in)
Enumeration Type Documentation
enum XPlaylistType
Defines the types of playlists available
Enumerator:
DEFAULT
VOD
EVENT
LIVE
VARIANT
Definition at line 97 of file m3u8.h.
Function Documentation
int8_t index_stream_list_add (IndexStreamList * list, int8_t program_id, uint64_t bandwidth, const char * codecs, const char * path)
Add new list record
Definition at line 502 of file m3u8.c.
References IndexStreamRecord::bandwidth, IndexStreamRecord::codecs, IndexStreamList::cur, IndexStreamList::head, IndexStreamRecord::next, IndexStreamRecord::path, IndexStreamRecord::prev, and IndexStreamRecord::program_id.
Referenced by index_stream_list_load_from().
int8_t index_stream_list_destroy (IndexStreamList * list)
Destroy index stream list
Definition at line 560 of file m3u8.c.
References IndexStreamRecord::codecs, IndexStreamList::head, IndexStreamRecord::next, and IndexStreamRecord::path.
int8_t index_stream_list_init (IndexStreamList * list)
Initializes new index stream stream
Definition at line 483 of file m3u8.c.
References IndexStreamRecord::bandwidth, IndexStreamRecord::codecs, IndexStreamList::cur, IndexStreamList::head, IndexStreamRecord::next, IndexStreamRecord::path, IndexStreamRecord::prev, and IndexStreamRecord::program_id.
Referenced by index_stream_list_load_from().
int8_t index_stream_list_load (IndexStreamList * list, const char * filename)
Load index stream list from file
Definition at line 623 of file m3u8.c.
References index_stream_list_load_from().
int8_t index_stream_list_load_from (IndexStreamList * list, FILE * in)
Load index stream list from stream
Each #EXT-X-STREAM-INF record spans two lines. Read the first line which may have the BANDWIDTH, CODECS, PROGRAM-ID attributes & parse them. The second line ALWAYS holds the PATH attribute.
Definition at line 640 of file m3u8.c.
References IndexStreamList::head, index_stream_list_add(), and index_stream_list_init().
Referenced by index_stream_list_load().
int8_t index_stream_list_write (IndexStreamList * list, const char * filename)
Write index stream list to file
Definition at line 580 of file m3u8.c.
References index_stream_list_write_to().
int8_t index_stream_list_write_to (IndexStreamList * list, FILE * out)
Write index stream list to stream
Definition at line 601 of file m3u8.c.
References IndexStreamRecord::bandwidth, IndexStreamRecord::codecs, IndexStreamList::head, IndexStreamRecord::next, IndexStreamRecord::path, and IndexStreamRecord::program_id.
Referenced by index_stream_list_write().
int8_t index_stream_record_set_bandwidth (IndexStreamRecord ** cur, uint64_t bandwidth)
Set bandwidth
Definition at line 439 of file m3u8.c.
int8_t index_stream_record_set_codecs (IndexStreamRecord ** cur, const char * codecs)
Set codecs
Definition at line 449 of file m3u8.c.
int8_t index_stream_record_set_path (IndexStreamRecord ** cur, const char * path)
Set path
Definition at line 466 of file m3u8.c.
int8_t index_stream_record_set_program_id (IndexStreamRecord ** cur, int8_t program_id)
Set program id
Definition at line 429 of file m3u8.c.
int8_t inf_destroy (InfRecord ** record)
Safely destroy an InfRecord
Definition at line 95 of file m3u8.c.
Referenced by record_list_destroy().
int8_t inf_init (InfRecord ** record)
Plain initialization of InfRecord
Definition at line 24 of file m3u8.c.
References InfRecord::name.
Referenced by record_list_add(), and record_list_add_more().
int8_t inf_set_length (InfRecord ** record, const float length)
Sets the length of the media-segment this record defines
Definition at line 38 of file m3u8.c.
Referenced by record_list_add(), and record_list_add_more().
int8_t inf_set_name (InfRecord ** record, const char * name)
Sets the name of the media segment
Definition at line 48 of file m3u8.c.
Referenced by record_list_add(), and record_list_add_more().
int8_t inf_set_path (InfRecord ** record, const char * path)
Sets the path of the media-segment
Definition at line 74 of file m3u8.c.
Referenced by record_list_add(), and record_list_add_more().
int8_t playlist_load (Playlist * playlist, const char * filename)
Read playlist from file Parse-Codes: 7 - START tag not found/incorrectly placed2 [#EXTM3U]
Definition at line 336 of file m3u8.c.
References playlist_load_from().
int8_t playlist_load_from (Playlist * playlist, FILE * in)
Read playlist from provided location
Definition at line 358 of file m3u8.c.
References Playlist::cur, Playlist::head, playlist_type_from(), record_list_add_more(), record_list_init(), Playlist::x_media_sequence, Playlist::x_target_duration, Playlist::x_type, and Playlist::x_version.
Referenced by playlist_load().
int8_t playlist_records_add (Playlist * playlist, const float length, const char * name, const char * path)
Easier access to PlaylistRecords add more
Definition at line 280 of file m3u8.c.
References Playlist::cur, and record_list_add_more().
int8_t playlist_records_destroy (Playlist * playlist)
Easier access to PlaylistRecords destroy
Definition at line 287 of file m3u8.c.
References Playlist::cur, Playlist::head, and record_list_destroy().
int8_t playlist_records_init (Playlist * playlist)
Easier access to PlaylistRecords init
Definition at line 272 of file m3u8.c.
References Playlist::cur, Playlist::head, and record_list_init().
XPlaylistType playlist_type_from (const char * str)
Convert string to playlist type
Definition at line 248 of file m3u8.c.
References DEFAULT, and PLAYLIST_TYPES_COUNT.
Referenced by playlist_load_from().
const char* playlist_type_str (const XPlaylistType type)
Convert playlist type to string
Definition at line 259 of file m3u8.c.
References DEFAULT, EVENT, LIVE, VARIANT, and VOD.
Referenced by playlist_write_to().
int8_t playlist_write (Playlist * playlist, const char * filename)
Write playlist to file
Definition at line 295 of file m3u8.c.
References playlist_write_to().
int8_t playlist_write_to (Playlist * playlist, FILE * out)
Write playlist to provided file
Definition at line 315 of file m3u8.c.
References Playlist::head, InfRecord::length, LIVE, InfRecord::name, PlaylistRecords::next, InfRecord::path, playlist_type_str(), PlaylistRecords::record, Playlist::x_media_sequence, Playlist::x_target_duration, Playlist::x_type, and Playlist::x_version.
Referenced by playlist_write().
int8_t record_list_add (PlaylistRecords ** cur, InfRecord * data)
Adds a new InfRecord to the playlist records list ** This is slightly more expensive than the other signatures of the same
Definition at line 123 of file m3u8.c.
References inf_init(), inf_set_length(), inf_set_name(), inf_set_path(), InfRecord::length, InfRecord::name, PlaylistRecords::next, and InfRecord::path.
int8_t record_list_add_more (PlaylistRecords ** cur, const float length, const char * name, const char * path)
Adds a new InfRecord to the playlist records list
Definition at line 155 of file m3u8.c.
References inf_init(), inf_set_length(), inf_set_name(), inf_set_path(), and PlaylistRecords::next.
Referenced by playlist_load_from(), and playlist_records_add().
int8_t record_list_destroy (PlaylistRecords ** head)
Destroys all records in the playlist
Definition at line 231 of file m3u8.c.
References inf_destroy(), PlaylistRecords::next, and PlaylistRecords::record.
Referenced by playlist_records_destroy().
int8_t record_list_init (PlaylistRecords ** head)
Initializes the playlist record list
Definition at line 109 of file m3u8.c.
References PlaylistRecords::next.
Referenced by playlist_load_from(), and playlist_records_init().
int8_t record_list_remove_at (PlaylistRecords ** head, uint16_t index)
Removes record number [index]
Definition at line 187 of file m3u8.c.
References PlaylistRecords::next.
int8_t record_list_remove_first_n (PlaylistRecords ** head, uint16_t n)
Removes the first [n] records from the playlist
Definition at line 209 of file m3u8.c.
References PlaylistRecords::next.