libsegmenter: segmenter.h File Reference
segmenter.h File Reference
#include <stdint.h>
#include <gst/gst.h>
Data Structures
struct _video_bag
struct _audio_bag
struct _transcoder_data
struct _video_params
struct _audio_params
struct _params
Defines
#define HLS_NAME "hlsegmenter"
#define HLS_VER "0.1"
#define VSCALE "video/x-raw-yuv,width=%d,height=%d"
Caps strings.
#define VRATE "video/x-raw-yuv, framerate=%d/1"
#define ACONV "audio/x-raw-int,channels=2"
#define ARES "audio/x-raw-int,rate=%d,channels=2"
Typedefs
typedef struct _video_bag VideoBag
typedef struct _audio_bag AudioBag
typedef struct _transcoder_data TranscoderData
typedef struct _video_params VideoParams
typedef struct _audio_params AudioParams
typedef struct _params Params
Functions
void grab_videoscale_caps (char *buffer, const uint16_t width, const uint16_t height)
void grab_videorate_caps (char *buffer, const uint8_t rate)
void grab_audioresample_caps (char *buffer, const uint16_t rate)
const int validate_params (const Params *params)
int segmenter_try (Params *params)
Define Documentation
#define ACONV "audio/x-raw-int,channels=2"
Definition at line 17 of file segmenter.h.
Referenced by segmenter_try().
#define ARES "audio/x-raw-int,rate=%d,channels=2"
Definition at line 18 of file segmenter.h.
Referenced by grab_audioresample_caps().
#define HLS_NAME "hlsegmenter"
Definition at line 11 of file segmenter.h.
Referenced by segmenter_try().
#define HLS_VER "0.1"
Definition at line 12 of file segmenter.h.
Referenced by segmenter_try().
#define VRATE "video/x-raw-yuv, framerate=%d/1"
Definition at line 16 of file segmenter.h.
Referenced by grab_videorate_caps().
#define VSCALE "video/x-raw-yuv,width=%d,height=%d"
Caps strings.
Definition at line 15 of file segmenter.h.
Referenced by grab_videoscale_caps().
Typedef Documentation
typedef struct _audio_bag AudioBag
typedef struct _audio_params AudioParams
typedef struct _params Params
typedef struct _transcoder_data TranscoderData
typedef struct _video_bag VideoBag
typedef struct _video_params VideoParams
Function Documentation
void grab_audioresample_caps (char * buffer, const uint16_t rate)
Grab customized audioresample caps string
Definition at line 31 of file segmenter.c.
References ARES.
Referenced by segmenter_try().
void grab_videorate_caps (char * buffer, const uint8_t rate)
Grab customized videorate caps string
Definition at line 22 of file segmenter.c.
References VRATE.
Referenced by segmenter_try().
void grab_videoscale_caps (char * buffer, const uint16_t width, const uint16_t height)
Grab customized videoscale caps string
Definition at line 13 of file segmenter.c.
References VSCALE.
Referenced by segmenter_try().
int segmenter_try (Params * params)
The segmenter must be callable from the server, and as such the following function is the entry-point
Initialize buffer
Initialize gstreamer
Create elements
Create empty pipeline
Set properties Set the location to transcode & segment
Set the multifilesink properties
Set the videorate properties
Set the aspectratiocrop properties
Set x264enc properties
Set ffenc_aac properties
Build the pipeline.
Connect to the pad-added signal
Start transcoding
Listen to the bus
Parse message
Free resources
Definition at line 45 of file segmenter.c.
References ACONV, _audio_bag::aconvcaps, _audio_bag::arescaps, _video_bag::aspectratiocrop, _params::audio_props, _transcoder_data::audiobag, _audio_bag::audioconvert, _audio_bag::audioresample, _video_params::bitrate, _audio_params::bitrate, BUFSIZE, _audio_bag::decqueue, _audio_bag::ffenc_aac, _video_bag::ffmpegcolourspace, _transcoder_data::filesrc, _video_params::framerate, grab_audioresample_caps(), grab_videorate_caps(), grab_videoscale_caps(), _video_params::height, HLS_NAME, HLS_VER, _params::in, _video_params::keyinterval, _transcoder_data::mpegtsmux, _video_bag::muxqueue, _audio_bag::muxqueue, _video_params::noisereduction, _params::out, _transcoder_data::pipeline, _transcoder_data::sink, _transcoder_data::source, _params::video_props, _transcoder_data::videobag, _video_bag::videorate, _video_bag::videoscale, _video_bag::vratecaps, _video_bag::vscalecaps, _video_params::width, and _video_bag::x264enc.
const int validate_params (const Params * params)
Validate incoming parameters
Definition at line 40 of file segmenter.c.